### ISSUE TITLE
Some questions about this code.

### ISSUE THREAD

**Issue by Haoqing-Wang** [cnguyen10/few_shot_meta_learning#1]
1. When calculating the calibration, why it adds some noise to the target in regression? 
Like this,
**outputs = outputs + (self.noise_std**2)*output_noises**
And should it be
**outputs = outputs + self.noise_std*output_noises**

2. As we all know, MAML can only calculate one value for a input, then how can it calculate the reliability diagram like fig 2(c) in you paper?

Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by cnguyen10** [comment]
Thank you @Haoqing-Wang for spotting the mistake. I have corrected.

To calculate the quantile calibration of MAML for regression, we simply calculate as the definition of quantile calibration. Note that MAML results in a point estimation, its predicted quantiles are the same, and so are the ground truth quantiles. Its performance curve is, therefore, a horizontal line going through that single point (which will be corrected in my camera-ready paper).
