### ISSUE TITLE
Consultation about the code

### ISSUE THREAD

**Issue by Yu979** [cnguyen10/few_shot_meta_learning#8]
Hello, I want to utilize **BMAML** and **PLATIPUS** to **multi-label sequence(1D) classification**, and the code is really helpful! The difficulty I face now is that there are too many files, and I don't know in what order should I modify the code. Could you please give me some advice and help?

**Comment by cnguyen10** [comment]
Hi Yu, when re-implementing these methods, I tried to put them into separate classes to make the code easy to read and maintain.
- For PLATIPUS, the implementation is done in `Platipus.py`. However, I found it hard to train PLATIPUS. One work-around solution is to train MAML first, then use the parameter obtained from MAML to train PLATIPUS.
- For BMAML, it is implemented in `Bmaml.py`. Note that the class inherits from `MLBaseClass` with some abstract methods. You should take a look at the two files when modifying BMAML for your need.

The two above are used to create an instance for each algorithm. For example, they include some functions used to train and test. The main procedure to train or test is then specified in `main.py`. Note that `main.py` is designed to run for any algorithms re-implemented in the repository.

Let me know if you still have any issues regarding to the understanding of my implementation.
