### ISSUE TITLE
Regression code

### ISSUE THREAD

**Issue by jihoontack** [cnguyen10/few_shot_meta_learning#9]
Hi, thank you for the wonderful code!

Are there any plans to open the code of regression models?

Thanks!
Jihoon

**Comment by cnguyen10** [comment]
Thank you for your interest in the code repository.

The regression was done in my previous implementation. However, such implementation utilized a customized data loading, which was inefficient and un-scalable for large datasets. After switching to `DataLoader` in Pytorch recently, I have not figured out how to integrate the sinusoidal/linear data generation into the `Dataset` class to include in the `DataLoader`.

I am planning to dedicate some time in November to do it.

**Comment by jihoontack** [comment]
Thank you for the information!

Also, thank you again for the great implementation!
